[workspace]
authors = ["saiaravind19"]
channels = ["conda-forge"]
name = "gazebo_terrain_generator"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
server = { cmd = "python scripts/server.py", cwd = "." }

[dependencies]
python = ">=3.12,<3.15"
flask = ">=2.0.1"
scikit-learn = ">=1.8.0,<2"
opencv = ">=4.10.0"
mercantile = ">=1.2.0"
requests = ">=2.25.1"
geopy = ">=2.4.1"
pillow = ">=9.0.0"
rasterio = ">=1.3.0"
shapely = ">=2.0.0"
pyproj = ">=3.4.0"
mapbox-vector-tile = ">=2.0.0"
trimesh = ">=4.11.0"
geopandas = ">=1.1.2"
scipy = ">=1.10.0"
pycollada = ">=0.9.3"
